create extension if not exists pgcrypto;

do $$
begin
  create type task_status as enum ('pending', 'in_progress', 'awaiting_approval', 'completed', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type task_action_type as enum ('outbound_call', 'send_email', 'send_sms', 'web_research', 'data_entry', 'opportunity_scan', 'briefing');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type execution_outcome as enum ('success', 'failure', 'partial', 'pending');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type opportunity_priority as enum ('low', 'medium', 'high', 'critical');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type opportunity_status as enum ('new', 'investigating', 'actioned', 'dismissed');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type consent_status as enum ('unknown', 'express', 'inferred', 'none');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type dnc_status as enum ('unknown', 'clear', 'registered', 'exempt', 'business_number');
exception when duplicate_object then null;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  goal_text text not null,
  status text not null default 'active' check (status in ('active', 'paused', 'completed', 'archived')),
  sub_goals jsonb not null default '[]'::jsonb,
  priority integer not null default 5 check (priority between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_queue (
  id bigint generated by default as identity primary key,
  goal_id bigint references public.goals(id) on delete set null,
  source text not null default 'task_generator',
  description text not null,
  priority_score numeric(6, 2) not null default 50 check (priority_score between 0 and 100),
  status task_status not null default 'pending',
  assigned_agent text,
  action_type task_action_type not null default 'web_research',
  action_payload jsonb not null default '{}'::jsonb,
  result_summary text,
  metadata jsonb not null default '{}'::jsonb,
  estimated_value numeric(12, 2) not null default 0,
  external_contact boolean not null default false,
  approval_required boolean not null default false,
  approval_nonce_hash text,
  approval_expires_at timestamptz,
  approval_used_at timestamptz,
  approval_requested_at timestamptz,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  idempotency_key text unique,
  claimed_at timestamptz,
  lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.task_queue
  add column if not exists attempt_count integer not null default 0 check (attempt_count >= 0),
  add column if not exists max_attempts integer not null default 3 check (max_attempts between 1 and 10);

create table if not exists public.execution_log (
  id bigint generated by default as identity primary key,
  task_id bigint references public.task_queue(id) on delete set null,
  action_type text not null,
  details jsonb not null default '{}'::jsonb,
  outcome execution_outcome not null default 'pending',
  error_message text,
  duration_ms integer,
  tokens_cost integer,
  api_spend_cents integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  task_id bigint references public.task_queue(id) on delete cascade,
  success text not null check (success in ('true', 'false', 'partial')),
  conversion_rate numeric(7, 4),
  cost_tokens integer,
  cost_cents integer not null default 0,
  lesson_learned text,
  strategy_used text,
  improvement_suggestion text,
  created_at timestamptz not null default now(),
  unique(task_id)
);

create table if not exists public.opportunities (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text,
  description text not null,
  priority opportunity_priority not null default 'medium',
  status opportunity_status not null default 'new',
  estimated_value numeric(12, 2),
  metadata jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, source_url)
);

create table if not exists public.system_config (
  config_key text primary key,
  config_value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

create table if not exists public.daily_metrics (
  date date primary key default current_date,
  tasks_generated integer not null default 0,
  tasks_completed integer not null default 0,
  tasks_failed integer not null default 0,
  calls_made integer not null default 0,
  emails_sent integer not null default 0,
  sms_sent integer not null default 0,
  api_spend_cents integer not null default 0,
  success_rate numeric(7, 4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  company_name text,
  contact_name text,
  phone text,
  email text,
  source text not null default 'manual',
  source_url text,
  consent_status consent_status not null default 'unknown',
  consent_evidence text,
  opted_out boolean not null default false,
  opted_out_at timestamptz,
  dnc_checked_at timestamptz,
  dnc_status dnc_status not null default 'unknown',
  allowed_contact_channels text[] not null default array[]::text[],
  timezone text not null default 'Australia/Perth',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.compliance_events (
  id bigint generated by default as identity primary key,
  contact_id bigint references public.contacts(id) on delete set null,
  task_id bigint references public.task_queue(id) on delete set null,
  event_type text not null,
  channel text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.outbound_messages (
  id bigint generated by default as identity primary key,
  task_id bigint references public.task_queue(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  channel text not null check (channel in ('sms', 'email')),
  provider text not null,
  provider_message_id text,
  provider_status text,
  from_address text,
  to_address text not null,
  subject text,
  body_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.retell_calls (
  id bigint generated by default as identity primary key,
  task_id bigint references public.task_queue(id) on delete set null,
  contact_id bigint references public.contacts(id) on delete set null,
  call_id text unique not null,
  event_status text not null default 'created',
  from_number text not null,
  to_number text not null,
  agent_id text,
  metadata jsonb not null default '{}'::jsonb,
  transcript text,
  call_analysis jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz
);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  signature_valid boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(provider, event_id)
);

create table if not exists public.policy_change_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  requested_by text not null,
  request_source text not null,
  request_text text not null,
  risk_level text not null check (risk_level in ('low', 'medium', 'high', 'critical')),
  protected_policy_keys text[] not null default array[]::text[],
  proposed_change_summary text not null,
  proposed_diff_or_config jsonb not null default '{}'::jsonb,
  status text not null default 'pending_review' check (status in ('pending_review', 'approved', 'rejected', 'applied', 'expired')),
  owner_approval_required boolean not null default true,
  owner_approved_at timestamptz,
  owner_approved_by text,
  expires_at timestamptz,
  applied_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text,
  audit_metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_task_queue_claim on public.task_queue(status, priority_score desc, created_at asc)
where status = 'pending';

create index if not exists idx_task_queue_approval on public.task_queue(status, approval_expires_at)
where status = 'awaiting_approval';

create unique index if not exists idx_goals_goal_text_unique on public.goals(goal_text);
create index if not exists idx_execution_log_task on public.execution_log(task_id, created_at desc);
create index if not exists idx_contacts_phone on public.contacts(phone) where phone is not null;
create index if not exists idx_contacts_email on public.contacts(lower(email)) where email is not null;
create index if not exists idx_opportunities_status on public.opportunities(status, priority, detected_at desc);
create index if not exists idx_retell_calls_call_id on public.retell_calls(call_id);
create index if not exists idx_policy_change_requests_status on public.policy_change_requests(status, risk_level, created_at desc);

drop trigger if exists goals_set_updated_at on public.goals;
create trigger goals_set_updated_at before update on public.goals
for each row execute function public.set_updated_at();

drop trigger if exists task_queue_set_updated_at on public.task_queue;
create trigger task_queue_set_updated_at before update on public.task_queue
for each row execute function public.set_updated_at();

drop trigger if exists opportunities_set_updated_at on public.opportunities;
create trigger opportunities_set_updated_at before update on public.opportunities
for each row execute function public.set_updated_at();

drop trigger if exists system_config_set_updated_at on public.system_config;
create trigger system_config_set_updated_at before update on public.system_config
for each row execute function public.set_updated_at();

drop trigger if exists daily_metrics_set_updated_at on public.daily_metrics;
create trigger daily_metrics_set_updated_at before update on public.daily_metrics
for each row execute function public.set_updated_at();

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at before update on public.contacts
for each row execute function public.set_updated_at();

drop trigger if exists outbound_messages_set_updated_at on public.outbound_messages;
create trigger outbound_messages_set_updated_at before update on public.outbound_messages
for each row execute function public.set_updated_at();

drop trigger if exists retell_calls_set_updated_at on public.retell_calls;
create trigger retell_calls_set_updated_at before update on public.retell_calls
for each row execute function public.set_updated_at();

create or replace function public.claim_next_task(worker_id text, lease_seconds integer default 900)
returns setof public.task_queue
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(
    (select (config_value #>> '{}')::boolean from public.system_config where config_key = 'kill_switch_active'),
    true
  ) then
    return;
  end if;

  return query
  with next_task as (
    select id
    from public.task_queue
    where status = 'pending'
      and (lease_expires_at is null or lease_expires_at < now())
    order by priority_score desc, created_at asc
    for update skip locked
    limit 1
  )
  update public.task_queue tq
  set
    status = 'in_progress',
    assigned_agent = worker_id,
    claimed_at = now(),
    lease_expires_at = now() + make_interval(secs => lease_seconds),
    updated_at = now()
  from next_task
  where tq.id = next_task.id
  returning tq.*;
end;
$$;

create or replace function public.increment_daily_metric(metric_name text, amount integer default 1)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if metric_name not in (
    'tasks_generated',
    'tasks_completed',
    'tasks_failed',
    'calls_made',
    'emails_sent',
    'sms_sent',
    'api_spend_cents'
  ) then
    raise exception 'Unsupported metric: %', metric_name;
  end if;

  execute format(
    'insert into public.daily_metrics(date, %I) values (current_date, $1)
     on conflict(date) do update set %I = public.daily_metrics.%I + $1, updated_at = now()',
    metric_name,
    metric_name,
    metric_name
  )
  using amount;
end;
$$;

create or replace function public.expire_old_approvals()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare changed integer;
begin
  update public.task_queue
  set
    status = 'cancelled',
    result_summary = coalesce(result_summary, 'Approval expired'),
    updated_at = now()
  where status = 'awaiting_approval'
    and approval_expires_at is not null
    and approval_expires_at < now();

  get diagnostics changed = row_count;
  return changed;
end;
$$;

create or replace function public.recover_stale_in_progress_tasks(
  stale_after_seconds integer default 1800,
  default_max_attempts integer default 3
)
returns table(task_id bigint, action text, attempt_count integer, max_attempts integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  rec record;
  next_attempt integer;
  configured_max integer;
  recovery_action text;
begin
  if stale_after_seconds < 60 then
    raise exception 'stale_after_seconds must be at least 60';
  end if;

  if default_max_attempts < 1 or default_max_attempts > 10 then
    raise exception 'default_max_attempts must be between 1 and 10';
  end if;

  for rec in
    select *
    from public.task_queue
    where status = 'in_progress'
      and coalesce(
        lease_expires_at,
        claimed_at + make_interval(secs => stale_after_seconds),
        updated_at + make_interval(secs => stale_after_seconds)
      ) < now()
    order by coalesce(lease_expires_at, updated_at) asc
    for update skip locked
  loop
    configured_max := coalesce(rec.max_attempts, default_max_attempts);
    next_attempt := coalesce(rec.attempt_count, 0) + 1;

    if next_attempt >= configured_max then
      recovery_action := 'failed';

      update public.task_queue
      set
        status = 'failed',
        attempt_count = next_attempt,
        result_summary = coalesce(result_summary, 'Task failed after stale in-progress recovery exceeded max attempts.'),
        lease_expires_at = null,
        claimed_at = null,
        assigned_agent = null,
        updated_at = now()
      where id = rec.id;
    else
      recovery_action := 'requeued';

      update public.task_queue
      set
        status = 'pending',
        attempt_count = next_attempt,
        lease_expires_at = null,
        claimed_at = null,
        assigned_agent = null,
        updated_at = now(),
        metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('last_stale_recovery_at', now())
      where id = rec.id;
    end if;

    insert into public.execution_log(task_id, action_type, details, outcome, error_message)
    values (
      rec.id,
      'stale_task_recovery',
      jsonb_build_object(
        'action', recovery_action,
        'previous_attempt_count', coalesce(rec.attempt_count, 0),
        'attempt_count', next_attempt,
        'max_attempts', configured_max,
        'previous_assigned_agent', rec.assigned_agent,
        'previous_lease_expires_at', rec.lease_expires_at
      ),
      case when recovery_action = 'failed' then 'failure'::execution_outcome else 'success'::execution_outcome end,
      case when recovery_action = 'failed' then 'Stale task exceeded max attempts' else null end
    );

    task_id := rec.id;
    action := recovery_action;
    attempt_count := next_attempt;
    max_attempts := configured_max;
    return next;
  end loop;
end;
$$;

alter table public.goals enable row level security;
alter table public.task_queue enable row level security;
alter table public.execution_log enable row level security;
alter table public.evaluations enable row level security;
alter table public.opportunities enable row level security;
alter table public.system_config enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.contacts enable row level security;
alter table public.compliance_events enable row level security;
alter table public.outbound_messages enable row level security;
alter table public.retell_calls enable row level security;
alter table public.webhook_events enable row level security;
alter table public.policy_change_requests enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all functions in schema public from anon, authenticated;

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;
